login: &login
  adapter: postgresql
  username: procore_db
  password: <%= ENV['POSTGRES_DB_PASSWORD'] %>

# DB1.DEVELOPER
development:
  <<: *login
  database: procore_lite1 # refresh on monday
#  database: procore_lite2 # refresh on tuesday
#  database: procore_lite3 # refresh on wednesday
#  database: procore_lite4 # refresh on thursday
#  database: procore_lite5 # refresh on friday
  host: 192.168.41.240 # In P4 Office
#  host: localhost # Out Of Office
#  port: 9999      # Out Of Office


test: &test
  <<: *login
#  database: procore_development
  database: procore_test_seed
  host: localhost
